# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-05-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0233_ensure_schema_and_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginControlAuthenticationAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_value', models.CharField(max_length=255)),
                ('is_availability', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'osf_login_control_authentication_attribute',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='LoginControlMailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('mail_address', models.CharField(max_length=320)),
                ('is_availability', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'osf_login_control_mail_address',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AddField(
            model_name='institution',
            name='login_availability_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='login_logic_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logincontrolmailaddress',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_control_mail_addresses', to='osf.Institution'),
        ),
        migrations.AddField(
            model_name='logincontrolauthenticationattribute',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_control_authentication_attributes', to='osf.Institution'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionentitlement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='institutionentitlement',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institutionentitlement',
            name='modifier',
        ),
        migrations.DeleteModel(
            name='InstitutionEntitlement',
        ),
    ]
