# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-06-11 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0234_merge_20240604_1014'),
        ('osf', '0234_auto_20240514_0329'),
    ]

    operations = [
    ]
